#!/usr/bin/env python3
"""Accelerated Hybrid A* using two action sets and two OPEN queues.

The algorithm keeps one shared mapping from each discretized state key to its
lowest-cost continuous node, but gives that node two queue views:

* the fine view uses the normal primitive length and all five steering angles;
* the coarse view uses a multiple of that length and only left, straight, and
  right maximum steering.

Each view has its own CLOSED set. Consequently, expanding a nonterminal state
from the coarse queue applies only the six coarse forward/reverse actions and
does not prevent the same current node from later receiving all ten fine actions.
When a cheaper representative replaces a state, both CLOSED marks are cleared
and the new node is inserted into both queues.

The scheduler prefers the coarse queue while its best priority is no greater
than ``queue_beta`` times the fine queue's best priority. Fine-generated nodes
may be demoted only in the coarse queue by ``origin_priority_factor`` so that
coarse-action branches can develop before coarse search follows every fine
branch. A maximum coarse burst then forces a fine expansion whenever fine work
remains, preventing starvation. Goal candidates and path costs are shared
across both views. Search stops after the configured post-goal expansion budget,
when both queues are exhausted, or at the global expansion limit; it does not
claim an optimality certificate.
"""

import heapq
import math
from numbers import Integral
from typing import Optional

import numpy as np

from hybrid_astar_planner import (
    Environment,
    ExpansionCallback,
    HeuristicMode,
    HybridAStar,
    Node,
    OpenEntry,
    ProgressCallback,
    SearchNodeState,
    StateKey,
    StateKeyMode,
    Vehicle,
    _validated_pose,
    sample_distances,
    validate_search_inputs,
    wrap,
)


class TwoQueueHybridAStar(HybridAStar):
    """Plan with fine and coarse OPEN queues over one shared state graph.

    The fine queue uses the base planner's primitive length and all five steering
    values. The coarse queue uses its configured coarse primitive length and
    ``{-max, 0, +max}``.
    Separate CLOSED sets let the current best representative of a nonterminal
    state receive both action sets.
    """

    def __init__(
        self,
        environment: Environment,
        vehicle: Vehicle,
        safety_margin: float,
        integration_step: float,
        collision_check_step: float,
        heuristic_mode: HeuristicMode = "default",
        state_key_mode: StateKeyMode = "pose_control",
        heuristic_weight: float = 1.0,
        coarse_heuristic_weight: Optional[float] = None,
        coarse_primitive_mult: int = 4,
        queue_beta: float = 1.5,
        origin_priority_factor: float = 2.0,
        corridor_width: Optional[float] = None,
        coarse_resolution: float = 1.0,
    ) -> None:
        """Configure the standard planner and the additional coarse queue.

        Args:
            environment: Planning bounds, obstacles, poses, and planner options.
            vehicle: Vehicle dimensions, wheelbase, and steering limits.
            safety_margin: Clearance added to every side during collision checking.
            integration_step: Spacing of reconstructed path samples.
            collision_check_step: Spacing of swept-path collision samples.
            heuristic_mode: Heuristic used by both queues.
            state_key_mode: Pose-only or control-aware state representation.
            heuristic_weight: Multiplier applied to ``h`` in the fine queue.
            coarse_heuristic_weight: Optional multiplier applied to ``h`` in the
                coarse queue; ``None`` uses ``heuristic_weight``.
            coarse_primitive_mult: Integer coarse/fine primitive-length ratio.
            queue_beta: Coarse eligibility factor in
                ``min_coarse <= queue_beta * min_fine``.
            origin_priority_factor: Priority penalty applied in the coarse queue
                to nodes generated by fine actions.
            corridor_width: Optional rear-axle radius around a coarse 2D A* path.
            coarse_resolution: Grid spacing used by coarse 2D A* in meters.

        Returns:
            None.

        Raises:
            ValueError: If a base-planner or two-queue option is invalid.
        """
        super().__init__(
            environment=environment,
            vehicle=vehicle,
            safety_margin=safety_margin,
            integration_step=integration_step,
            collision_check_step=collision_check_step,
            heuristic_mode=heuristic_mode,
            state_key_mode=state_key_mode,
            heuristic_weight=heuristic_weight,
            corridor_width=corridor_width,
            coarse_resolution=coarse_resolution,
        )

        if coarse_heuristic_weight is not None and (
            not math.isfinite(coarse_heuristic_weight) or coarse_heuristic_weight < 0.0
        ):
            raise ValueError("coarse_heuristic_weight must be a finite non-negative number or None")
        if not isinstance(coarse_primitive_mult, Integral) or isinstance(coarse_primitive_mult, bool):
            raise ValueError("coarse_primitive_mult must be an integer")
        if coarse_primitive_mult < 1:
            raise ValueError("coarse_primitive_mult must be at least 1")
        if not math.isfinite(queue_beta) or queue_beta < 1.0:
            raise ValueError("queue_beta must be finite and at least 1.0")
        if not math.isfinite(origin_priority_factor) or origin_priority_factor < 1.0:
            raise ValueError("origin_priority_factor must be finite and at least 1.0")

        self.coarse_heuristic_weight = (
            heuristic_weight if coarse_heuristic_weight is None else coarse_heuristic_weight
        )
        self.queue_beta = queue_beta
        self.origin_priority_factor = origin_priority_factor
        self.coarse_primitive_length = int(coarse_primitive_mult) * self.primitive_length
        self.coarse_steer_indices = (0, len(self.steers) // 2, len(self.steers) - 1)

        # Both primitive sets use the same swept-collision spacing. The exact
        # endpoint is always included, so sampling does not change edge geometry.
        self._coarse_collision_distances = np.asarray(
            sample_distances(self.coarse_primitive_length, collision_check_step),
            dtype=float,
        )

        # Reconstruction supports parent chains containing either edge length.
        self._integration_distances_by_length[self.coarse_primitive_length] = np.asarray(
            sample_distances(self.coarse_primitive_length, integration_step),
            dtype=float,
        )

        # Queue-specific counters exist only on the two-queue planner.
        self.fine_expansion_count = 0
        self.coarse_expansion_count = 0
        self.last_expansion_queue = "fine"

    def _publish_search_state(
        self,
        fine_closed: set[StateKey],
        coarse_closed: set[StateKey],
        nodes: dict[StateKey, Node],
        progress_callback: ProgressCallback,
    ) -> None:
        """Publish the union frontier from the fine and coarse searches.

        A state is displayed as closed when both queue views are closed. Normally
        this means both action sets expanded the current best representative;
        accepted terminals are instead closed in both views without successors.

        Args:
            fine_closed: State keys closed in the five-steer queue view.
            coarse_closed: State keys closed in the three-steer queue view.
            nodes: Current best-known node for every generated state key.
            progress_callback: Consumer of selected snapshots and display states.

        Returns:
            None.
        """
        if not nodes:
            return

        states: list[SearchNodeState] = []
        for key, node in nodes.items():
            heuristic = self.heuristic(node.x, node.y, node.yaw)
            states.append(
                SearchNodeState(
                    node=node,
                    heuristic=heuristic,
                    total_estimate=node.cost + self.heuristic_weight * heuristic,
                    # A shared state is globally closed when both queue views are
                    # closed, including terminals deliberately closed without successors.
                    closed=key in fine_closed and key in coarse_closed,
                )
            )

        state_tuple = tuple(states)
        open_states = tuple(state for state in state_tuple if not state.closed)
        if not open_states:
            return
        best_total = min(open_states, key=lambda state: state.total_estimate)
        best_heuristic = min(state_tuple, key=lambda state: state.heuristic)
        progress_callback(
            self.expansion_count,
            self._snapshot(best_total.node, best_total.heuristic),
            self._snapshot(best_heuristic.node, best_heuristic.heuristic),
            state_tuple,
        )

    def _finish_search(
        self,
        best_terminal: Node,
        best_terminal_expansion: int,
        goal: tuple[float, float, float],
        fine_closed: set[StateKey],
        coarse_closed: set[StateKey],
        nodes: dict[StateKey, Node],
        live_plot_every: int,
        progress_callback: Optional[ProgressCallback],
        expansion_callback: Optional[ExpansionCallback],
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, Node]:
        """Publish final two-queue state, report, and reconstruct the path.

        Args:
            best_terminal: Lowest-cost terminal node found by the search.
            best_terminal_expansion: Expansion count when the terminal was accepted.
            goal: Nominal rear-axle ``(x, y, yaw)`` goal pose.
            fine_closed: State keys expanded with the standard action set.
            coarse_closed: State keys expanded with the coarse action set.
            nodes: Current best-known node for every generated state key.
            live_plot_every: Positive when final search state should be published.
            progress_callback: Optional consumer of search-progress snapshots.
            expansion_callback: Optional consumer of the final expansion count.

        Returns:
            The reconstructed path, directions, steering values, and terminal node.
        """
        if expansion_callback is not None:
            expansion_callback(self.expansion_count)
        if progress_callback is not None and live_plot_every > 0:
            self._publish_search_state(
                fine_closed,
                coarse_closed,
                nodes,
                progress_callback,
            )
        self.report_goal("Best", best_terminal, best_terminal_expansion, goal)
        path, directions, steers = self.reconstruct(best_terminal)
        return path, directions, steers, best_terminal

    def plan(
        self,
        start: tuple[float, float, float],
        goal: tuple[float, float, float],
        max_expansions: int,
        live_plot_every: int = 0,
        progress_callback: Optional[ProgressCallback] = None,
        expansion_callback: Optional[ExpansionCallback] = None,
        post_goal_expansions: int = 0,
        max_consecutive_coarse_expansions: int = 10,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, Node]:
        """Search with fine and coarse queues over one shared state graph.

        For nonterminal states, the globally available fine queue expands ten
        forward/reverse actions over five steering values. The coarse queue expands
        six actions of its configured length over ``{-max, 0, +max}`` steering.
        It is eligible when ``min_coarse <= queue_beta * min_fine``. At most
        ``max_consecutive_coarse_expansions`` coarse expansions are allowed while
        a fine state remains available; the next expansion is then forced fine.

        Args:
            start: Initial rear-axle ``(x, y, yaw)`` pose.
            goal: Nominal rear-axle goal pose.
            max_expansions: Maximum fine-plus-coarse action-set expansions.
            live_plot_every: Publish live state every N expansions; zero disables it.
            progress_callback: Optional consumer of live-search snapshots.
            expansion_callback: Optional lightweight expansion-count callback.
            post_goal_expansions: Additional expansions after the first goal.
            max_consecutive_coarse_expansions: Maximum coarse burst while fine
                work remains; zero forces fine whenever the fine queue is non-empty.

        Returns:
            Reconstructed path, directions, steering values, and terminal node.

        Raises:
            ValueError: If arguments are invalid or start/goal is in collision.
            RuntimeError: If no accepted terminal is found before termination.
        """
        validate_search_inputs(max_expansions, live_plot_every, post_goal_expansions)
        if not isinstance(max_consecutive_coarse_expansions, Integral) or isinstance(
            max_consecutive_coarse_expansions, bool
        ):
            raise ValueError("max_consecutive_coarse_expansions must be an integer")
        if max_consecutive_coarse_expansions < 0:
            raise ValueError("max_consecutive_coarse_expansions must be non-negative")
        start = _validated_pose("start", start)
        goal = _validated_pose("goal", goal)

        # Reset per-search state and invalidate a Dijkstra map built for an old goal.
        self.goal = goal
        self._dijkstra_cost_to_goal = None
        self.expanded = []
        self.expansion_count = 0
        self.fine_expansion_count = 0
        self.coarse_expansion_count = 0
        self.unique_expanded_state_count = 0
        self.last_expansion_queue = "fine"
        if self.collides(*start):
            raise ValueError("Start pose (including safety margin) is in collision")
        if self.collides(*goal):
            raise ValueError("Goal pose (including safety margin) is in collision")
        self._prepare_corridor(start, goal)

        # Both queues share one lowest-cost representative per state key. Their
        # separate CLOSED sets track which action set is still pending.
        start_node = Node(
            *start,
            0.0,
            None,
            1,
            int(np.argmin(np.abs(self.steers))),
            0.0,
        )
        start_key = self._state_key(start_node, initial=True)
        nodes: dict[StateKey, Node] = {start_key: start_node}
        fine_closed: set[StateKey] = set()
        coarse_closed: set[StateKey] = set()

        start_heuristic = self.heuristic(*start)
        fine_queue: list[OpenEntry] = [
            (
                start_node.cost + self.heuristic_weight * start_heuristic,
                start_heuristic,
                -start_node.cost,
                0,
                start_key,
                start_node,
            )
        ]
        coarse_queue: list[OpenEntry] = [
            (
                start_node.cost + self.coarse_heuristic_weight * start_heuristic,
                start_heuristic,
                -start_node.cost,
                0,
                start_key,
                start_node,
            )
        ]

        serial = 0
        best_terminal: Optional[Node] = None
        best_terminal_expansion: Optional[int] = None
        first_goal_expansion: Optional[int] = None

        # Bound coarse bursts so the globally available fine action set cannot
        # be starved. Once the limit is reached, the next eligible expansion is fine.
        coarse_streak = 0
        expanded_state_keys: set[StateKey] = set()
        open_exhausted = False

        while self.expansion_count < max_expansions:
            if self._post_goal_budget_complete(
                first_goal_expansion,
                post_goal_expansions,
            ):
                assert best_terminal is not None
                assert best_terminal_expansion is not None
                return self._finish_search(
                    best_terminal,
                    best_terminal_expansion,
                    goal,
                    fine_closed,
                    coarse_closed,
                    nodes,
                    live_plot_every,
                    progress_callback,
                    expansion_callback,
                )

            fine_min = self._peek_best_open_priority(fine_queue, fine_closed, nodes)
            coarse_min = self._peek_best_open_priority(coarse_queue, coarse_closed, nodes)
            if fine_min is None and coarse_min is None:
                open_exhausted = True
                break

            coarse_is_preferred = coarse_min is not None and (
                fine_min is None or coarse_min <= self.queue_beta * fine_min
            )
            use_coarse = coarse_is_preferred and (
                fine_min is None or coarse_streak < max_consecutive_coarse_expansions
            )
            if use_coarse:
                active_queue = coarse_queue
                active_closed = coarse_closed
                selected_primitive_length = self.coarse_primitive_length
                collision_distances = self._coarse_collision_distances
                steer_indices = self.coarse_steer_indices
                queue_name = "coarse"
            else:
                active_queue = fine_queue
                active_closed = fine_closed
                selected_primitive_length = self.primitive_length
                collision_distances = self._collision_distances
                steer_indices = self.steer_indices
                queue_name = "fine"

            current_entry = self._pop_best_open(active_queue, active_closed, nodes)
            if current_entry is None:
                continue
            current_key, current = current_entry
            active_closed.add(current_key)
            expanded_state_keys.add(current_key)
            self.unique_expanded_state_count = len(expanded_state_keys)
            self.last_expansion_queue = queue_name
            self.expansion_count += 1
            if use_coarse:
                coarse_streak += 1
                self.coarse_expansion_count += 1
            else:
                coarse_streak = 0
                self.fine_expansion_count += 1

            if expansion_callback is not None and self.expansion_count % 100 == 0:
                expansion_callback(self.expansion_count)

            # A node is terminal only when both configured pose tolerances hold.
            position_error = math.hypot(current.x - goal[0], current.y - goal[1])
            yaw_error = abs(wrap(current.yaw - goal[2]))
            if self.expansion_count % 10 == 0:
                self.expanded.append((current.x, current.y))

            if position_error <= self.position_tolerance and yaw_error <= self.yaw_tolerance:
                if best_terminal is None or current.cost < best_terminal.cost:
                    best_terminal = current
                    best_terminal_expansion = self.expansion_count
                    self.report_goal("Accepted", current, self.expansion_count, goal)
                if first_goal_expansion is None:
                    first_goal_expansion = self.expansion_count

                # A cost-terminal is absorbing. Closing both queue views prevents
                # either action set from expanding it again.
                fine_closed.add(current_key)
                coarse_closed.add(current_key)
                continue

            # Expand only the action set associated with the selected queue.
            for direction in (1, -1):
                for steer_index in steer_indices:
                    endpoint = self.check_primitive(
                        current,
                        direction,
                        steer_index,
                        collision_distances,
                    )
                    if endpoint is None:
                        continue
                    successor_cost = self._successor_cost(
                        current,
                        direction,
                        steer_index,
                        selected_primitive_length,
                    )
                    successor_key = self._state_key_from_values(
                        *endpoint,
                        direction,
                        steer_index,
                    )
                    incumbent = nodes.get(successor_key)
                    if incumbent is None or successor_cost + 1e-9 < incumbent.cost:
                        successor = Node(
                            *endpoint,
                            successor_cost,
                            current,
                            direction,
                            steer_index,
                            selected_primitive_length,
                        )
                        nodes[successor_key] = successor

                        # An improved shared state must be reconsidered with both
                        # action sets, even if an older representative was closed.
                        fine_closed.discard(successor_key)
                        coarse_closed.discard(successor_key)
                        serial += 1
                        heuristic = self.heuristic(
                            successor.x,
                            successor.y,
                            successor.yaw,
                        )
                        fine_priority = successor.cost + self.heuristic_weight * heuristic
                        coarse_priority = successor.cost + self.coarse_heuristic_weight * heuristic

                        # Lower heap values are expanded first. Fine-generated
                        # nodes are penalized only in the coarse queue; nodes
                        # generated by coarse actions keep their base priority.
                        if not use_coarse:
                            coarse_priority *= self.origin_priority_factor

                        fine_entry: OpenEntry = (
                            fine_priority,
                            heuristic,
                            -successor.cost,
                            serial,
                            successor_key,
                            successor,
                        )
                        coarse_entry: OpenEntry = (
                            coarse_priority,
                            heuristic,
                            -successor.cost,
                            serial,
                            successor_key,
                            successor,
                        )
                        heapq.heappush(fine_queue, fine_entry)
                        heapq.heappush(coarse_queue, coarse_entry)

            # Periodically publish the union of states open in either queue.
            if (
                progress_callback is not None
                and live_plot_every > 0
                and self.expansion_count % live_plot_every == 0
            ):
                self._publish_search_state(
                    fine_closed,
                    coarse_closed,
                    nodes,
                    progress_callback,
                )

        post_goal_budget_complete = self._post_goal_budget_complete(
            first_goal_expansion,
            post_goal_expansions,
        )
        if best_terminal is not None:
            if not post_goal_budget_complete and not open_exhausted:
                print(
                    "\nWarning: the search limit was reached before the requested "
                    "post-goal expansion budget was completed.",
                    flush=True,
                )
            assert best_terminal_expansion is not None
            return self._finish_search(
                best_terminal,
                best_terminal_expansion,
                goal,
                fine_closed,
                coarse_closed,
                nodes,
                live_plot_every,
                progress_callback,
                expansion_callback,
            )

        corridor_detail = ""
        if self.corridor is not None:
            corridor_detail = (
                f" inside corridor width {self.corridor_width:.3f} m at coarse "
                f"resolution {self.corridor_grid_resolution:.3f} m"
            )
        raise RuntimeError(
            f"No path found after {self.expansion_count} action-set expansions"
            f"{corridor_detail} "
            f"({self.fine_expansion_count} fine, "
            f"{self.coarse_expansion_count} coarse; two_queue=True)"
        )
